### PR TITLE
Terraria

### PR DESCRIPTION
**Pull request by UnluckyLucky**
Hey, Daniel. I'm that person who suggested Terraria. I might have used Minecraft as a base, as you can see, but this could be a start. If you allow this I'll be really happy, and maybe- who knows? I might make one for another game! Thanks, man. If you see this, I would be happy to make more, alright? OK, thank you, and bye!

### CODE REVIEW

**Comment by Lockyy** [comment]
This looks good. I made a couple fixes to make sure it ran but other than that this is good. You can check out the fixes here so you can see what went wrong: https://github.com/Lockyy/Scenario-Generator/commit/7615cf5839f016d248b27b2a02672b62a7fb8f60

**Comment by Lockyy** [comment]
The generator is now live: http://www.scenariogenerator.net/game/terraria

**Comment by UnluckyLucky** [comment]
Thanks! I made some fixies as some Mine-Craft things were still lingering in there. You might want to add those so nobody gets confused.

**Comment by Lockyy** [comment]
Done, thanks for the heads up

**Pull request merged**
